# Site settings
title: Writer Theme
email: andreas@rudischhauser.de
description: > # Writer Theme is a responsive template
 focussed on typography, minimal design and
  quality photography built using the Jekyll platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About me : ['About me', '/author/andi', 'fa-user']
  Contact : ['Contact', '/contact', 'fa-plane']
single_footer: '<p>The writer community loves your content. Writer &copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About me : ['About me', '/author/andi', 'fa-user']
    Contact : ['Contact', '/contact', 'fa-plane']


# Build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
